CC = g++

all:
	$(CC) Expr.cpp List.cpp Pgm.cpp Value.cpp Datatype.cpp Func.cpp Parser.cpp \
		Stmt.cpp Main.cpp -o parser -g
m:
	$(CC) expr.cpp list.cpp pgm.cpp value.cpp datatype.cpp func.cpp parser.cpp \
		stmt.cpp mymain.cpp asura.cpp -o m -g
