CC = g++

all:
	$(CC) Expr.cpp Pgm.cpp Value.cpp Func.cpp Parser.cpp Stmt.cpp Main.cpp -o parser -g
m:
	$(CC) expr.cpp list.cpp pgm.cpp value.cpp datatype.cpp func.cpp parser.cpp \
		stmt.cpp mymain.cpp asura.cpp -o m -g
