CC = g++

all:
	$(CC) expr.cc list.cc pgm.cc value.cc datatype.cc func.cc parser.cc \
		stmt.cc main.cc asura.cc -o parser -g
m:
	$(CC) expr.cc list.cc pgm.cc value.cc datatype.cc func.cc parser.cc \
		stmt.cc mymain.cc asura.cc -o m -g
